package corba;


/**
* corba/UrgenceService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Urgence.idl
* dimanche 7 décembre 2025 12 h 15 GMT+01:00
*/

public interface UrgenceService extends UrgenceServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UrgenceService
