package corba;

import org.omg.CORBA.portable.*;
import org.omg.PortableServer.Servant;

/**
* corba/UrgenceServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Urgence.idl
* dimanche 7 décembre 2025 12 h 15 GMT+01:00
*/

public abstract class UrgenceServicePOA extends Servant
    implements corba.UrgenceServiceOperations, InvokeHandler
{

    // Méthodes CORBA
    private static java.util.Hashtable _methods = new java.util.Hashtable();
    static {
        _methods.put("addUrgence", new Integer(0));
    }

    public OutputStream _invoke(String $method,
                                InputStream in,
                                ResponseHandler $rh)
    {
        OutputStream out = null;
        Integer __method = (Integer)_methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue()) {
            case 0:  // corba/UrgenceService/addUrgence
            {
                String type = in.read_string();
                String chambre = in.read_string();
                String declarant = in.read_string();

                // Correction : utiliser long pour correspondre à l'IDL
                long $result = this.addUrgence(type, chambre, declarant);

                out = $rh.createReply();
                out.write_long((int)$result); // CORBA long est 32 bits, cast nécessaire si addUrgence retourne long Java
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    }

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:corba/UrgenceService:1.0"
    };

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return (String[])__ids.clone();
    }

    public UrgenceService _this() 
    {
        return UrgenceServiceHelper.narrow(super._this_object());
    }

    public UrgenceService _this(org.omg.CORBA.ORB orb) 
    {
        return UrgenceServiceHelper.narrow(super._this_object(orb));
    }

} // class UrgenceServicePOA
