package corba;

/**
* corba/UrgenceServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Urgence.idl
* dimanche 7 décembre 2025 12 h 15 GMT+01:00
*/

public final class UrgenceServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.UrgenceService value = null;

  public UrgenceServiceHolder ()
  {
  }

  public UrgenceServiceHolder (corba.UrgenceService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.UrgenceServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.UrgenceServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.UrgenceServiceHelper.type ();
  }

}
