package corba;


/**
* corba/UrgenceServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Urgence.idl
* dimanche 7 d�cembre 2025 12 h 15 GMT+01:00
*/

public interface UrgenceServiceOperations 
{
  long addUrgence (String type, String chambre, String declarant);
} // interface UrgenceServiceOperations
