package corba;


/**
* corba/UrgenceServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Urgence.idl
* dimanche 7 décembre 2025 12 h 15 GMT+01:00
*/

abstract public class UrgenceServiceHelper
{
  private static String  _id = "IDL:corba/UrgenceService:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.UrgenceService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.UrgenceService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.UrgenceServiceHelper.id (), "UrgenceService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.UrgenceService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UrgenceServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.UrgenceService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.UrgenceService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.UrgenceService)
      return (corba.UrgenceService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._UrgenceServiceStub stub = new corba._UrgenceServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.UrgenceService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.UrgenceService)
      return (corba.UrgenceService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._UrgenceServiceStub stub = new corba._UrgenceServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
